# vim: set ft=yaml ts=2 expandtab:
#
# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
name: 'Ansible Collection Info'
description: 'Get Info about remote ansible collection'
inputs:
  targeted_branch:
    description: 'The targeted branch for remote requests'
    required: true
  filename:
    description: 'The filename of  a tar.gz if the collection is not remote'
  repository:
    description: 'Optional repo namespace/name'
    default: ${{ github.repository }}
  python_version:
    description: The version of the python interpreter
    type: string
    default: 3
outputs:
  namespace:
    value: ${{ steps.info.outputs.namespace }}
  collection_name:
    value: ${{ steps.info.outputs.collection_name }}

runs:
  using: "composite"

  steps:

    - name: setup python
      if: inputs.python_version != '3'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Get Info about installed collection
      shell: bash
      id: info
      env:
        CI_REPO: ${{ inputs.repository }}
        CI_REF: ${{ inputs.targeted_branch }}
        SERVER: raw.githubusercontent.com
        FILENAME: ${{ inputs.filename }}
        PYTHON: python${{ inputs.python_version }}
      run: |
        if test -n "$FILENAME"; then
            # local mode
            read namespace name rest < <(echo "$FILENAME" | sed 's/-/ /g')
        else
            $PYTHON -c "
        import sys, yaml, json
        y=yaml.safe_load(sys.stdin.read())
        print(json.dumps(y))" < \
            <(curl -s "https://$SERVER/$CI_REPO/$CI_REF/galaxy.yml")|\
            jq -r '.namespace + " " + .name' >/tmp/ansiblecollectioninfo.txt
            read namespace name </tmp/ansiblecollectioninfo.txt
        fi

        test -n "$namespace"
        test -n "$name"

        echo "namespace=$namespace" >>$GITHUB_ENV
        echo "collection_name=$name" >>$GITHUB_ENV
        echo "namespace=$namespace" >>$GITHUB_OUTPUT
        echo "collection_name=$name" >>$GITHUB_OUTPUT

...
