# vim: set ft=yaml ts=2 expandtab:
#
# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

# call it with
# if: always()
#
name: BuildAnsibleArtefact
on:  # yamllint disable-line rule:truthy
  # make it reusable
  workflow_call:
    inputs:
      targeted_branch:
        type: string
        required: true
      src:
        description: The directory of the collection source
        type: string
        required: true
      dest:
        description: The destination filename
        type: string
        required: true
      
jobs:

  - name: Build the ansible collection
    run: ansible-galaxy collection build ${{ inputs.src }}

  - name: Assert that the destination file was created
    env:
      DEST: ${{ inputs.dest }}
    run:
      test -f "$DEST"

  - name: Upload the Artifact
    uses: actions/upload-artifact@v4
    with:
      name: ansible-collections-${{ inputs.targeted_branch }}
      path: ${{ inputs.dest }}
      if-no-files-found: error
      overwrite: true
...
