# vim: set ft=yaml ts=2 expandtab:
#
# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
name: PREPARE
on:  # yamllint disable-line rule:truthy
  # make it reusable
  workflow_call:
    inputs:
      targeted_branch:
        type: string
    outputs:
      ref:
        description: "The name of the target branch for downloads from other repositories"
        value: ${{ steps.stepx.outputs.branch }}
      
jobs:
  selectbranch:
    runs-on: ubuntu-22.04
    steps:
      - name: Return the targeted branch for downloads from other repositories
        id: stepx
        run: |
            if test "${{ inputs.targeted_branch }}" = "main"; then
                branch="main"
            elif test "${{ github.ref_name }}" = "main"; then
                branch="main"
            else
                branch="dev"
            fi
            echo branch="$branch" >> $GITHUB_OUTPUT
            echo "two=bla" >> $GITHUB_OUTPUT
            echo branch=$branch
...
