# vim: set ft=yaml ts=2 expandtab:
#
# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

name: ANSIBLECOLLECTION

on: # yamllint disable-line rule:truthy

  # make it reusable
  workflow_call:
    inputs:
      env_name:
        type: string
    outputs:
      env_name:
        description: The name of the targeted environment.
        value: ${{ jobs.setenv.outputs.env_name }}

jobs:
  setenv:
    outputs:
      env_name: ${{ steps.set_name.outputs.env_name }}
    steps:
      - name: Set the name of the environment
        id: set_name
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "::set-output name=env_name::prod"
          else
            echo "::set-output name=env_name::dev"
          fi
    
...
